# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Marc Denman
tagline:          'IT Technican'
description:      'An IT Technican at <a href="http://huish.ac.uk" target="_blank">Richard Huish College</a>'
url:              http://marcdenman.co.uk

author:
  name:           'Marc Denman'
  url:            http://marcdenman.co.uk

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/marcdenman