# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Marc Denman
tagline:          'Software Engineer'
description:      'A software engineer based in Taunton, Somerset'
url:              http://marcdenman.co.uk

author:
  name:           'Marc Denman'
  url:            http://marcdenman.co.uk

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/marcdenman
